# Generated by Django 4.0.2 on 2022-02-28 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcommingBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcommingbookby', to='api.author')),
            ],
        ),
    ]
